Voltage monitoring afgerond
Someone-s-out-there/ProjectCarHAN pull request #85
Opened 2023-12-14 13:02 UTC by GhostJulian

### Spanning monitor is nu afgerond

Door de functie `getVoltage()` aan te roepen krijg je de werkelijke spanning dat uit de voltage divider komt.

Dit is tevens getest met een multimeter. De afwijking is ± 0,05 volt. De stroom naar de AVR stroomt 3,4µA, op 7,70 volt accuspanning.

2023-12-15 11:43 UTC, Someone-s-out-there requested changes

2023-12-15 11:43 UTC, Someone-s-out-there commented on RobotCar/Functions/Voltage_monitoring/Voltage_monitoring.c
> +}
Bottom of the file

2023-12-15 11:43 UTC, Someone-s-out-there commented on RobotCar/Functions/Voltage_monitoring/Voltage_monitoring.c
> +// GetVoltage() returns the acual voltage with a deviation of 0,05 volts
Make doxygen comments

2023-12-17 13:32 UTC, Someone-s-out-there approved these changes
Looks good to me

2023-12-19 10:01 UTC, hsdqghq approved these changes
Ziet er duidelijk uit

2023-12-23 18:53 UTC, merged